services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        - VITE_BACKEND_URL=http://192.168.178.22:3000
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://192.168.178.22:3000
      - PORT=3000
    restart: unless-stopped
    networks:
      - quiz-game
networks:
  quiz-game:
    driver: bridge